      - name: Update Gist raw JSON
        env:
          GH_TOKEN: ${{ secrets.GIST_TOKEN }}
          GIST_ID:  ${{ secrets.FGI_GIST_ID }}
        run: |
          set -e
          # 1) fgi.json の中身を 1行JSONに
          COMPACT=$(jq -c . fgi.json)
          # 2) それを「JSON文字列」にエスケープ（Gist APIは string 必須）
          CONTENT=$(printf '%s' "$COMPACT" | jq -Rs .)
          # 3) PATCH ペイロード生成
          cat > payload.json <<EOF
          { "files": { "fgi.json": { "content": $CONTENT } } }
          EOF

          echo "== PATCH to Gist ${GIST_ID} =="
          curl -sS -X PATCH \
            -H "Authorization: Bearer ${GH_TOKEN}" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/gists/${GIST_ID}" \
            -d @payload.json | tee patch_out.json

          # 失敗の兆候を検出
          if jq -e 'has("message") and .message != null' patch_out.json >/dev/null; then
            echo "Gist API error:"
            cat patch_out.json
            exit 1
          fi
